name: Chatting App CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install --prefix server && npm install --prefix public/chat-app
      - run: npm run build --prefix public/chat-app
